FROM nginx
#COPY index.html /usr/share/nginx/html
#COPY docker.png /usr/share/nginx/html
#COPY traefik.png /usr/share/nginx/html
#COPY ocloud.png /usr/share/nginx/html
#COPY nginx.png /usr/share/nginx/html
#COPY oracle.png /usr/share/nginx/html

